export enum StoryFields {
  id = 'id',
  bannerImageUrl = 'bannerImageUrl',
  title = 'title',
  abstract = 'abstract',
  outline = 'outline',
  publishDate = 'publishDate',
  eventDate = 'eventDate',
  tags = 'tags',
  story = 'story',
  minutesToRead = 'minutesToRead',
  language = 'language',
  slug = 'slug',
  featured = 'featured',
  publishStatus = 'publishStatus',
  readMoreStorySlugs = 'readMoreStorySlugs',
}
